### ISSUE TITLE
voc dataset train error

### ISSUE THREAD

**Issue by JunShao-Hub** [wizyoung/YOLOv3_TensorFlow#130] opened 2019-08-06 13:49 UTC
totalMemory: 3.95GiB freeMemory: 3.51GiB
2019-08-06 21:44:11.757852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2019-08-06 21:44:46.350787: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-06 21:44:46.350811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2019-08-06 21:44:46.350818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2019-08-06 21:44:46.350947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3239 MB memory) -> physical GPU (device: 0, name: Quadro M1200, pci bus id: 0000:01:00.0, compute capability: 5.0)
INFO:tensorflow:Restoring parameters from ./data/darknet_weights/yolov3.ckpt

----------- start to train -----------

  0%|          | 0/2759 [00:00<?, ?it/s]2019-08-06 21:45:03.316142: W tensorflow/core/framework/op_kernel.cc:1306] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'astype'
Traceback (most recent call last):

  File "/home/kcadmin/PycharmProjects/darknet/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 158, in __call__
    ret = func(*args)

  File "/home/kcadmin/PycharmProjects/YOLOv3_TensorFlow/utils/data_utils.py", line 214, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode, letterbox_resize)

  File "/home/kcadmin/PycharmProjects/YOLOv3_TensorFlow/utils/data_utils.py", line 146, in parse_data
    img = random_color_distort(img)

  File "/home/kcadmin/PycharmProjects/YOLOv3_TensorFlow/utils/data_aug.py", line 253, in random_color_distort
    img = random_brightness(img, brightness_delta)

  File "/home/kcadmin/PycharmProjects/YOLOv3_TensorFlow/utils/data_aug.py", line 247, in random_brightness
    img = img.astype(np.float32)

AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by wizyoung** [comment] 2019-08-09 15:41
duplicate of https://github.com/wizyoung/YOLOv3_TensorFlow/issues/123

**Closed by wizyoung** 2019-08-09 15:41 UTC
