### ISSUE TITLE
training probrem

### ISSUE THREAD

**Issue by CherishineNi** [wizyoung/YOLOv3_TensorFlow#32] opened 2019-03-22 06:19 UTC
How to solve this problem, great god, help me!
![6IL{)0B4 WZ4L84BL`9G 4X](https://user-images.githubusercontent.com/44666138/54804169-84a57580-4cad-11e9-8a39-81e64f6e7722.png)

**Comment by madhu-korada** [comment] 2019-03-24 06:14
same problem.

**Comment by wizyoung** [comment] 2019-06-28 16:44
duplicate of https://github.com/wizyoung/YOLOv3_TensorFlow/issues/33

**Closed by wizyoung** 2019-06-28 16:44 UTC
